name: ERNIE-RNA-cpu
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - asttokens=2.4.1
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.7
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=2.0.1
  - ffmpeg=4.3
  - freetype=2.10.4
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.29.3
  - ipython=8.12.0
  - jbig=2.1
  - jedi=0.19.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - lame=3.100
  - lcms2=2.12
  - lerc=2.2.1
  - libdeflate=1.7
  - libffi=3.4.4
  - libiconv=1.17
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.3.0
  - libuv=1.43.0
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nest-asyncio=1.6.0
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - olefile=0.47
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.3
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=23.3.1
  - platformdirs=4.2.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.16
  - python-dateutil=2.9.0
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytorch=1.10.0
  - torchaudio=0.10.0
  - torchvision=0.11.0
  - pytz=2023.3.post1
  - pyzmq=25.1.2
  - requests=2.31.0
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - tzdata=2024a
  - urllib3=2.1.0
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.0
  - pip:
    - antlr4-python3-runtime==4.8
    - bitarray==2.9.2
    - cffi==1.16.0
    - colorama==0.4.6
    - cython==3.0.9
    - fairseq==0.12.2
    - hydra-core==1.0.7
    - lxml==5.1.0
    - omegaconf==2.0.6
    - portalocker==2.8.2
    - protobuf==4.25.3
    - pycparser==2.21
    - pyyaml==6.0.1
    - regex==2023.12.25
    - sacrebleu==2.4.1
    - tabulate==0.9.0
    - tensorboardx==2.6.2.2
    - tqdm==4.66.2
