name: ERBR-RNA-cpu
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - bottleneck
  - numexpr
  - ipykernel
  - ipython
  - jupyter_client
  - jupyter_core
  - requests
  - pillow
  - packaging
  - tqdm
  - ffmpeg
  - pytorch  # 先不锁版本，后面再 pip 安装指定版本
  - pip=24.0
  - pip:
      - fairseq==0.12.2
      - hydra-core==1.0.7
      - omegaconf==2.0.6
      - sacrebleu==2.4.1
      - antlr4-python3-runtime==4.8
      - tensorboardx==2.6.2.2
      - protobuf==4.25.3
      - cython==3.0.9
      - bitarray==2.9.2
      - lxml==5.1.0
      - regex==2023.12.25
      - tabulate==0.9.0
      - pyyaml==6.0.1
      - portalocker==2.8.2

